name: Check Xcode and Make

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  check-xcode-make:
    runs-on: [macos-14] # Adjust to your organization runner if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Packer Build
        run:   packer build \
               /images/macos/templates/macOS-14.arm64.anka.pkr.hcl
